CREATE SEQUENCE SPRINGNUMBER_SEQUENCE START WITH 1 INCREMENT BY 1;

CREATE TABLE T_SPRING_NUMBER (
  ID IDENTITY NOT NULL PRIMARY KEY ,
  SPRING_NUMBER INT
);

INSERT INTO T_SPRING_NUMBER VALUES (SPRINGNUMBER_SEQUENCE.NEXTVAL, 123);
INSERT INTO T_SPRING_NUMBER VALUES (SPRINGNUMBER_SEQUENCE.NEXTVAL, 5);
INSERT INTO T_SPRING_NUMBER VALUES (SPRINGNUMBER_SEQUENCE.NEXTVAL, 7);